INSERT INTO manga (title, author, genre, description, rating, imageurl) VALUES ('Naruto', 'Masashi Kishimoto', 'Fantasy', 'Naruto Uzumaki is a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village.', 4.7, 'http://localhost:8080/images/naruto_cover_page.jpg'),
                                                                               ('Omniscient Reader''s Viewpoint', 'Sing Shong', 'Comedy', 'Dokja was an average office worker whose sole interest was reading his favorite web novel, Three Ways to Survive the Apocalypse. But when the novel suddenly becomes reality, Dokja must fight to survive in a world that is now populated by monsters and characters from the novel.', 4.4, 'http://localhost:8080/images/omniscient_readers_viewpoint_cover_page.jpg'),
                                                                               ('Windbreaker', 'NII Satoru', 'Action', 'This is the story of how delinquent Sakura becomes a hero! Furin High School, made of durable concrete, displays the test results and the strongest fighters. This spring, Sakura Haruka decides to reach the top of Furin and learns of a strange group called the "Furin Defenders" received to protect the city and its inhabitants. He becomes part of it, and the battle to protect the city begins!', 4.8, 'http://localhost:8080/images/windbreaker_cover_page.jpg'),
                                                                               ('The Beginning After the End', 'TurtleMe', 'Action', 'King Gray has unrivaled power, wealth and prestige in a world dominated by combat power. However, loneliness usually appears precisely among those who have great power. Few people know, but under the glamorous appearance of a powerful king hides the shell of a man devoid of purpose and will.', 4.9, 'http://localhost:8080/images/the_beginning_after_the_end.jpg'),
                                                                               ('White Blood', 'Kohei Horikoshi', 'Romance', 'Many years ago, a miracle happened – a shimmering baby was born. Since then, people with special powers – quirks -have been born everywhere. However, alas, not all of them use their abilities for good.… Fortunately, professional heroes are always on guard, who will not allow absolute evil to take over! If you want to become a hero, enroll in the hero academy and unlock your potential!', 4.2, 'http://localhost:8080/images/white_blood_cover_page.jpg'),
                                                                               ('Сволочь', 'Джон Фаулз', 'Drama', 'История об интригующем и загадочном человеке, который вертит судьбы окружающих людей, используя хитрость и обман.', 3.9, 'http://localhost:8080/images/scum_cover_page.jpg'),
                                                                               ('Милый Дом 6', 'Carnby Kim', 'Horror', 'После того как мир погрузился в хаос, превратив людей в монстров, главный герой Хён Су пытается выжить, сражаясь с ужасами в своём доме.', 4.0, 'http://localhost:8080/images/sweet_home_cover_page.jpg'),
                                                                               ('Steel Ball Run', 'Hirohiko Araki', 'Adventure', 'Захватывающая гонка через США в 19 веке, где участники используют уникальные способности, чтобы победить в турнире и получить приз.', 5.0,'http://localhost:8080/images/steel_ball_run_cover_page.jpg'),
                                                                               ('One Punch-Man', 'ONE', 'Comedy', 'Сайтама – герой, который может побеждать любого врага одним ударом. Его проблема? Жизнь становится скучной, когда все слишком легко.', 1.2, 'http://localhost:8080/images/one_punch_man_cover_page.jpg'),
                                                                               ('Solo Leveling', 'Chugong', 'Fantasy', 'Сунг Джин-Ву, самый слабый охотник, однажды получает силу, которая позволяет ему становиться сильнее, побеждая монстров в подземельях.', 3.7, 'http://localhost:8080/images/solo_leveling_cover_page.jpg');

